### ISSUE TITLE
[style] 로그인 뷰 UI 작업

### ISSUE THREAD

**Issue by hueeel** [APPSCHOOL1-REPO/finalproject-checkit#1]
## 🗣️  설명

프로토타입의  로그인 뷰 UI 작업입니다.
실제 작동은 구현되지 않습니다.

## ✅ Todo

- [x] 애플 로그인 버튼 만들기
- [x] 카카오 로그인 버튼 만들기
- [x] 네이버 로그인 버튼 만들기
- [x] 구글 로그인 버튼 만들기
- [x] 앱 로고 만들기
