### ISSUE TITLE
[Feat] 동아리 생성시 이미지를 입력받는 작업

### ISSUE THREAD

**Issue by hueeel** [APPSCHOOL1-REPO/finalproject-checkit#102]
## 🗣️  설명

동아리 생성이 이미지를 입력받고 서버에 저장하는 작업입니다.

## ✅ Todo

- [x] PhotosUI를 이용한 이미지 가져오는 작업
- [x] 가져온 이미지를 스토리지에 저장
- [x] 동아리를 fetch할때 스토리지로 부터 이미지 패치
