### ISSUE TITLE
[Feat] 출석체크뷰 데이터 연동

### ISSUE THREAD

**Issue by blaire-pi** [APPSCHOOL1-REPO/finalproject-checkit#103]
## 🗣️  설명

출석체크뷰 파이어베이스 데이터 연동

## ✅ Todo

- [x] CheckitCardVeiw에 group데이터 패치
- [x] CheckitCardView에 schedule 데이터 패치
- [x] 동아리를 탈퇴했을 때를 가정 -> 출석체크 뷰에서 마지막으로 본 카드페이지가 탈퇴한 동아리에 해당하는 내용일 때 이전 인덱스의 카드가 show 되도록 count변수 값 조정
