### ISSUE TITLE
[Style] UI 피드백 개선작업 02

### ISSUE THREAD

**Issue by hwangyeri** [APPSCHOOL1-REPO/finalproject-checkit#109]
## 🗣️  설명

UI 피드백 개선작업 02

## ✅ Todo

- [x] 동아리 전체 패딩 너비 통일시키기
- [x] 동아리 정보 - 수정 버튼 위치 조정
- [x] 동아리 정보 - 삭제 버튼 크기 조정
- [x] 마이페이지 문의하기 레이블 변경
- [x] 마이페이지 오픈소스 라이선스 레이블 중복 제거
- [x] 마이페이지 문의하기 - 회원탈퇴 추가
