### ISSUE TITLE
[Style] GroupMainView UI 수정

### ISSUE THREAD

**Issue by hwangyeri** [APPSCHOOL1-REPO/finalproject-checkit#122]
## 🗣️  설명

GroupMainView UI 수정

## ✅ Todo

- [x] Scroll indicator 위치 조정
- [x] Title lable, Navigation Title로 변경
- [x] Plus button, Navigation Toolbar로 변경
