### ISSUE TITLE
[Refactor] Group 모델에 총 인원수 필드 추가

### ISSUE THREAD

**Issue by hueeel** [APPSCHOOL1-REPO/finalproject-checkit#127]
## 🗣️  설명

Group 모델에 동아리원의 총 인원수를 나타내는 필드를 추가합니다.

## ✅ Todo

- [x] Group 모델에 동아리원의 총 인원수를 나타내는 필드 추가
- [x] 동아리 생성시 인원수 1로 설정
- [x] 동아리 참가시 인원수 + 1로 설정
