### ISSUE TITLE
[Feature] 지각비 정산 뷰, 수정 및 데이터 연결

### ISSUE THREAD

**Issue by ryuchanghwi** [APPSCHOOL1-REPO/finalproject-checkit#140]
## 🗣️  설명

[Feature] 지각비 정산 뷰

## ✅ Todo

- [x] 카테고리 옆에 출석 카운트 추가하기
- [x] 카테고리를 눌렀을 때 해당 출석 현황 인원 보여주기
- [x] navigaionTitle inline으로 수정하기
