### ISSUE TITLE
[Feat] 동아리 정보를 불러오는 기능 구현

### ISSUE THREAD

**Issue by hueeel** [APPSCHOOL1-REPO/finalproject-checkit#149]
## 🗣️  설명

카테고리 - 세부 탭인 동아리 정보 에서 데이터를 불러오는 기능을 구현합니다.

## ✅ Todo

- [x] 동아리 정보에서 데이터를 불러오는 작업을 합니다.
- [x] 방장 동아리 정보뷰와 데이터 연동
- [x] 운영진, 동아리원 동아리 정보뷰와 데이터 연동
