### ISSUE TITLE
[Feat] 방장이 동아리 구성원 정보를 수정하는 작업

### ISSUE THREAD

**Issue by hueeel** [APPSCHOOL1-REPO/finalproject-checkit#158]
## 🗣️  설명

방장이 동아리 구성원 정보를 수정 및 동아리 삭제 작업을 수행합니다.

## ✅ Todo

- [x] 동아리원 정렬 작업 (방장 - 운영진 - 구성원)
- [x] 동아리원 강퇴하는 기능
- [x] 동아리원 역할 변경 기능
