### ISSUE TITLE
[Feat] 동아리 정보를 수정 하는 작업

### ISSUE THREAD

**Issue by hueeel** [APPSCHOOL1-REPO/finalproject-checkit#159]
## 🗣️  설명

동아리 편집(이름 또는 사진) 초대 링크를 공유 하는 작업입니다.

## ✅ Todo

- [x] 동아리 수정 toolbar 버튼 만들기
- [x] 동아리원이 동아리 나가기 기능
- [x] 동아리 참가시 실시간 패치
- [x] #194
- [x] 방장이 동아리 삭제하기 기능
