### ISSUE TITLE
[Refactor] 동아리원 현재 인원수를 인원 제한수로 변경 작업

### ISSUE THREAD

**Issue by hueeel** [APPSCHOOL1-REPO/finalproject-checkit#171]
## 🗣️  설명

동아리원 현재 인원수를 나타내는 작업인 member_count 필드를 인원수 제한을 나타내는 member_limit로 변경하는 작업을 진행합니다.

## ✅ Todo

- [x] 동아리 모델에서 memberCount -> memberLimit
- [x] 관련된 부수적인 코드 수정
- [x] 동아리 참가시 정원이 초과하는지 확인하는 기능 구현
