### ISSUE TITLE
[Style] 출석부 UI 수정

### ISSUE THREAD

**Issue by ryuchanghwi** [APPSCHOOL1-REPO/finalproject-checkit#185]
## 🗣️  설명

[Style] 출석부 UI 수정

## ✅ Todo

- [ ] 출석부 방장뷰 UI수정
- [ ] 출석부 개인 UI수정
- [ ] 출석부 출석현황 수정 뷰 UI수정
