### ISSUE TITLE
[Style] 출석부 전체적인 UI 수정 및 기능 수정

### ISSUE THREAD

**Issue by ryuchanghwi** [APPSCHOOL1-REPO/finalproject-checkit#207]
## 🗣️  설명

이슈에 대해 설명해주세요.

## ✅ Todo

- [x] 출석부 생성 시 인원들 공결 -> 결석
- [x] 출석부 정산여부 레이블 추가
- [x] 총 결석비, 총 지각비 -> 미정산 금액으로 레이블 변경
- [ ] 출석 유저 cell 통일 시키기
