### ISSUE TITLE
[Style] CheckMap, GroupDetail 피드백 반영 뷰 수정

### ISSUE THREAD

**Issue by HHCHO0220** [APPSCHOOL1-REPO/finalproject-checkit#212]
## 🗣️  설명

맵뷰 비활성 버튼 색상 수정 및 동아리 목록 정렬 수정, 이미지와 텍스트 간격 조정

## ✅ Todo

- [x] 맵뷰 비활성 버튼 색상 수정
- [x] 동아리 목록에서 방장인 동아리 우선 정렬
- [x] 동아리 목록 이미지왐 텍스트 간격 조정
