### ISSUE TITLE
[Style] 동아리탭 동아리 정보 뷰 

### ISSUE THREAD

**Issue by ryuchanghwi** [APPSCHOOL1-REPO/finalproject-checkit#22]
## 🗣️  설명

동아리탭에 동아리 정보 뷰에서 개인과, 방장의 ui를 만들고자 합니다. 

## ✅ Todo

- [x] 동아리 메인 이미지뷰 작업
- [x] 동아리 제목과 소개글 작업
- [x] 동아리 멤버 리스트 작업(개인)
- [ ] 동아리 멤버 리스트 작업(방장)
