### ISSUE TITLE
[Feat] 동아리 수정시 실시간 반영 

### ISSUE THREAD

**Issue by hueeel** [APPSCHOOL1-REPO/finalproject-checkit#247]
## 🗣️  설명

동아리 수정시 실시간 반영 작업입니다.

## ✅ Todo

- [x] 동아리 수정시 실시간 반영
- [x] 동아리 수정시 토스트 메시지 screen
- [x] 이미지가 없는 동아리 수정시 앱 종료 버그 픽스
