### ISSUE TITLE
[Style] EmptyView 생성 및 UI 작업 (Group Main, Group Schedule, Group Attendance)

### ISSUE THREAD

**Issue by hwangyeri** [APPSCHOOL1-REPO/finalproject-checkit#257]
## 🗣️  설명

EmptyView 생성 및 UI 작업 (Group Main, Group Schedule, Group Attendance)

## ✅ Todo

- [x] GroupEmptyView UI 수정 작업
- [x] ScheduleEmptyView 생성 및 UI 작업
- [x] AttendanceEmptyView 생성 및 UI 작업
