### ISSUE TITLE
[Style] 동아리 탭 뷰 수정

### ISSUE THREAD

**Issue by HHCHO0220** [APPSCHOOL1-REPO/finalproject-checkit#26]
## 🗣️  설명

동아리 탭 뷰 수정 작업 예정입니다.

## ✅ Todo

- [x] 카테고리 뷰 보더에서 밑줄로 수정
- [x] myYellow -> myOrange로 색깔 수정
- [x] 동아리 일정 뷰 순서 조정
- [x] 동아리 일정 뷰 지각, 결석, 출석 마크 삭제
- [x] 출석부(개인) 뷰 수정
