### ISSUE TITLE
[style] 마이페이지 뷰 UI 작업

### ISSUE THREAD

**Issue by ryuchanghwi** [APPSCHOOL1-REPO/finalproject-checkit#3]
## 🗣️  설명

프로토타입으로 사용될 마이페이지 뷰 구현입니다. 

## ✅ Todo

- [x] 프로필 편집 뷰 만들기
- [x] 프리미엄 요금제 알아보기 버튼 만들기
- [x] 문의하기 버튼 만들기
- [x] 로그아웃 버튼 만들기
- [x] 문의하기 뷰 만들기
