### ISSUE TITLE
[Refactor] 스케줄 모델에 지각 인정 시간 필드 추가 작업

### ISSUE THREAD

**Issue by hueeel** [APPSCHOOL1-REPO/finalproject-checkit#308]
## 🗣️  설명

스케줄 모델에 지각 인정 시간 필드를 추가합니다.

## ✅ Todo

- [x] 스케줄 모델에 지각 인정 시간 필드 추가
- [x] 스케줄 추가 뷰 지각 인정 시간 추가
- [x] 스케줄 디테일 뷰에 지각 인정 시간 추가
- [x] 스케줄 수정 뷰에 지각 인정 시간 추가
- [x] 스케줄 생성시 장소 선택안하면 토스트 메시지 추가
