### ISSUE TITLE
[Feat] 출석체크 탭 동아리 카드 수정

### ISSUE THREAD

**Issue by blaire-pi** [APPSCHOOL1-REPO/finalproject-checkit#315]
## 🗣️  설명

출석체크 탭 동아리 카드의 디테일 정보 및 정렬을 처리

## ✅ Todo

- [x] 오늘 일정 출석체크 버튼 활성화
- [x] 지난 일정 데이터는 보이지 않게 처리
- [x] 과거 일정만 있는 동아리의 경우 따로 레이블이 주어지도록 작업
- [x] 현재와 가까운 순으로 정렬
- [x] 삭제시 실시간 반영
