### ISSUE TITLE
[Style] 기종 화면 크기에 따른 사이즈 조절 및 다크모드 UI 수정

### ISSUE THREAD

**Issue by HHCHO0220** [APPSCHOOL1-REPO/finalproject-checkit#318]
## 🗣️  설명

기종 화면 크기에 따른 사이즈 조절 및 다크모드 UI 수정

## ✅ Todo

- [x] 체크 카드 뷰 기종 화면 크기에 따른 사이즈 조절
- [x] 마이페이지 텍스트 버튼 클릭 범위 확대
- [x] 다크모드 UI 수정
