### ISSUE TITLE
[Style] 구성원 출석부 다크모드 UI 수정, 탭바 배경색 수정, 맵뷰 하단 패딩 조정

### ISSUE THREAD

**Issue by HHCHO0220** [APPSCHOOL1-REPO/finalproject-checkit#323]
## 🗣️  설명

이슈에 대해 설명해주세요.
- 구성원 출석부 다크모드 UI 수정, 탭바 배경색 수정, 맵뷰 하단 패딩 조정

## ✅ Todo

- [x] 구성원 출석부 다크모드 UI 수정
- [x] 탭바 배경색 수정
- [x] 맵뷰 하단 패딩 조정
