### ISSUE TITLE
[FIX] 수정사항

### ISSUE THREAD

**Issue by hwangyeri** [APPSCHOOL1-REPO/finalproject-checkit#335]
## 🗣️  설명

아까 수정사항 다시 반영함

## ✅ Todo

- [x] App icon && logo 수정
- [x] 탭바 컬러 변경
- [x] OnBoardingView 텍스트 오타 수정
