### ISSUE TITLE
[Style] 동아리 메인뷰 및 모달뷰 UI 수정

### ISSUE THREAD

**Issue by hwangyeri** [APPSCHOOL1-REPO/finalproject-checkit#35]
## 🗣️  설명

동아리 메인뷰 및 모달 뷰 UI 수정

## ✅ Todo

- [x] 동아리 메인 뷰 UI 수정
- [x] 동아리 메인 뷰 버튼 수정
- [ ] 액션 시트 추가
- [x] 동아리 참가하기 뷰 UI 수정
- [x] 동아리 개설하기 뷰 UI 수정
- [x] 동아리 개설하기 뷰 이미지 변경
