### ISSUE TITLE
[Fix] 로그인 관련 에러들 수정

### ISSUE THREAD

**Issue by soletree** [APPSCHOOL1-REPO/finalproject-checkit#365]
## 🗣️  설명

로그인 관련 에러들을 수정합니다. 

## ✅ Todo

- [x] Kakao Login 시 processView가 나타나도록 수정
- [x] 카카오 로그인 에러 수정 
- [x] 회원탈퇴 메서드와 연결
