### ISSUE TITLE
동아리 메인뷰 UI 작업

### ISSUE THREAD

**Issue by hwangyeri** [APPSCHOOL1-REPO/finalproject-checkit#4]
## 🗣️  설명

프로토타입의 동아리 탭 UI 작업
1. 동아리 메인뷰 UI 작업

## ✅ Todo

- [x] 동아리 리스트 UI
- [x] 동아리 개설하기 버튼 만들기
- [ ] 동아리 개설하기 모달 UI
- [x] 동아리 참가하기 버튼 만들기
- [x] 동아리 참가하기 모달 UI
- [x] Assets AccentColor, myGreen 컬러 변경
- [x] Assets 동아리 이미지 추가
- [x] Modifier 버튼 속성 만들기
