### ISSUE TITLE
[Feat] 동아리 메인뷰에서 동아리를 데이터와 뷰 연동작업

### ISSUE THREAD

**Issue by hueeel** [APPSCHOOL1-REPO/finalproject-checkit#56]
## 🗣️  설명

동아리 메인뷰에서 동아리를 데이터와 뷰 연동작업입니다.

## ✅ Todo

- [x] 서버에서 가져온 데이터를 동아리메인뷰와 데이터 연동
- [x] 동아리 메인뷰의 반복되는 뷰를 cell view로 분리
- [x] 데이터 모델을 Identifiable 프로토콜을 따르도록 준수
