### ISSUE TITLE
[Feat] 동아리 참가하기 기능 구현 작업

### ISSUE THREAD

**Issue by hueeel** [APPSCHOOL1-REPO/finalproject-checkit#65]
## 🗣️  설명

유저가 초대코드를 입력하면 해당 동아리에 가입되는 기능을 구현합니다.

## ✅ Todo

- [x] 유저가 초대코드를 통해 동아리에 가입
- [x] 유저가 입력한 초대코드가 올바른 초대코드 인지 유효성 검사
- [x] 이미 가입된 동아리 초대코드인지 확인하는 로직 구현
