### ISSUE TITLE
[Feat] CheckItMainView 수정

### ISSUE THREAD

**Issue by HHCHO0220** [APPSCHOOL1-REPO/finalproject-checkit#69]
## 🗣️  설명

출석체크 카드 넘기는 뷰 수정작업입니다.

## ✅ Todo

- [x] Card 구조체 생성
- [x] ChectICard 파일 수정
- [x] CheckMainView 파일 수정
