### ISSUE TITLE
[Style] MyPageView UI 수정

### ISSUE THREAD

**Issue by hwangyeri** [APPSCHOOL1-REPO/finalproject-checkit#83]
## 🗣️  설명

마이페이지 탭 - 마이페이지 뷰 - 문의하기 뷰
MyPageView UI 수정

## ✅ Todo

- [x] MyPageView UI 수정
- [x] 문의하기 - 오픈소스 라이센스 중복 수정
- [x] 프로필 변경 버튼 주석처리
