### ISSUE TITLE
[Style] 동아리 탭 목업 뷰 작업

### ISSUE THREAD

**Issue by HHCHO0220** [APPSCHOOL1-REPO/finalproject-checkit#9]
## 🗣️  설명

피그마 도안대로 동아리 탭 파트의 목업 뷰 그리는 작업입니다.

## ✅ Todo

- [x] 동아리 탭 상단 카테고리 구분하기
- [x] 동아리 일정 뷰
- [x] 동아리 일정 추가하기 뷰
- [x] 동아리 출석 뷰 (개인)
