### ISSUE TITLE
[Feat] CheckItCard Indicator

### ISSUE THREAD

**Issue by HHCHO0220** [APPSCHOOL1-REPO/finalproject-checkit#90]
## 🗣️  설명

CheckItCard 사이즈 수정 및 인디케이터 추가 작업

## ✅ Todo

- [x] CheckItCard 사이즈 수정
- [x] CheckItCard 인디케이터 추가 작업
- [x] 맵핀 심볼 사이즈 수정
